# Generated by Django 5.0.6 on 2024-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('clothing_type', models.CharField(choices=[('classic', 'Classic'), ('casual', 'Casual'), ('sport', 'Sport')], max_length=10)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=10)),
                ('image', models.ImageField(upload_to='media/clothes')),
            ],
        ),
    ]
